### ISSUE TITLE
Version extraction for --keep-duplicate-crates is incorrect

### ISSUE THREAD

**Issue by mzabaluev** [matthiaskrgr/cargo-cache#81]
[The code](https://github.com/matthiaskrgr/cargo-cache/blob/aadd87443491b340aee177e985281c9fef67a84d/src/remove.rs#L48) to split the package version from the name does not account for post-version suffixes denoting pre-releases in semver.
These are some of the strings I get from running `ls -1 ~/.cargo/registry/src/github.com-1ecc6299db9ec823/ | grep -Eo -- '-[^-]*$' | LC_COLLATE=C sort -u`:

```
-alpha.19
-alpha.2
-alpha.4
-beta.1
-beta.2
-pre.2
-pre.3
-preview1
```

I think a more robust way to split the version part from the name is to walk back the dash-separated segments until one is found starting with a digit.

**Comment by matthiaskrgr** [comment]
Thanks, I did indeed not think of alpha/beta etc prefixes when implementing this... :sweat_smile: 

I'll check if I can outsource the version parsing to the [semver](https://crates.io/crates/semver) crate instead... :)

**Comment by matthiaskrgr** [comment]
Turns out that using semver does not help here since I need to figure out what part of the filename belongs to the version and which one belongs to the crate name...

@mzabaluev  I implemented your idea of splitting at `-` and checking for a segment that starts with a digit (everything after that should belong to the version) :+1: 

If you find any other issues, please let me know!
